remote_theme: poole/hyde

# Dependencies
markdown:         kramdown
highlighter:      rouge 
#highlighter:      pygments

# Setup
title:            Guía de exploits
url:               https://fundacion-sadosky.github.io
baseurl:           /guia-escritura-exploits/

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled:     true

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
repo: https://github.com/poole/hyde
