remote_theme: poole/hyde
# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Guía de exploits
#tagline:          'A Jekyll theme'
#description:      'Basada en Insecure programming de <a href="">Gera</a>'
#url:              http://hyde.getpoole.com
baseurl:          https://fundacion-sadosky.github.io/guia-escritura-exploits/

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled:     true
#  collections: true

#collections:
#  buffer-overflow
#    output: true


author:
  name:           'Teresa Alberto'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
